name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dev deps
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt
      - name: Lint
        run: |
          flake8 src
          isort --check-only src
          black --check src
          mypy src
      - name: Tests
        run: pytest -v
